#!/usr/bin/env zsh
#DESC# python packages for pyenv version#DESC#

set -euo pipefail

DOTFILES_DIR=~/.dotfiles
source "${DOTFILES_DIR}/local/include/hook-helpers.zsh"

for ver in $(pyenv versions --bare); do
  export PYENV_VERSION=$ver

  pyenv version | colorize green

  if ! pyenv exec pip --version |& colorize black bold | offset; then
    echo skipping | colorize yellow | offset
    continue
  fi

  # These are important and should be done first.
  pyenv exec pip install --upgrade pip wheel | offset
  echo

  pyenv exec pip \
    install \
    --upgrade \
    --requirement ~/.config/tools-update/pip.txt \
    | offset
  echo
done

# EOF
