collapse_simple_statement = "Always"
column_width = 120
indent_type = "Spaces"
indent_width = 2
line_endings = "Unix"
no_call_parentheses = false
quote_style = "AutoPreferSingle"

[sort_requires]
enabled = false
