language: ruby

before_script:
- "git clone https://github.com/syngan/vim-vimlint /tmp/vim-vimlint"
- "git clone https://github.com/ynkdir/vim-vimlparser /tmp/vim-vimlparser"

script:
- "sh /tmp/vim-vimlint/bin/vimlint.sh -l /tmp/vim-vimlint -p /tmp/vim-vimlparser -v autoload"

notifications:
  email:
    on_failure: "never"
    on_success: "never"
  pushover:
    on_success: "change"
    api_key:
      secure: "e2joFHX80Vmi1mBK/mKfs2TBmCNBDHGRvhvWbPz+clddPUKDDjIIe24iyAKqAR743iC0SvOyBHLLAKFh5Ovf/JJLwMZtf2jT8hiP/d2GEBK0LRXAM4viYloSwhx1sj4ofsZHVxGtIl2ikNllT1pv6GmXoAwSry7LE+Zp9AMv7iY="
    users:
      secure: "J8ciphNPfp2YDd3f6cVd3WzDRrbcGVbQoBTf7uuwwGLUpgKTKamKFc9d0WbAH031ZaH8tA3LdCb+y1q3nFtRgpD7u4qroWbuGyq+V0xSgpck+wnRNx4Y8RUGQhCGUHv9AT9VheO4UEimLw8STMQqQJ+diDxpDn6xNtZnK3z8dcQ="
