#!/bin/bash
# Set BASH_ENV to this file to have these variables always set.

tracestate="$(shopt -po xtrace)"
set +o xtrace

export BASH_ENV="${BASH_SOURCE[0]:-${HOME}/.bashenv}"

for bashenv_env in ~/.bash/startup/*-env.bash; do
  if [[ -r ${bashenv_env} ]]; then
    # shellcheck disable=SC1090
    . "${bashenv_env}"
  fi
done
unset bashenv_env

# MUST BE LAST
eval "${tracestate}"
unset tracestate
# EOF
