# Needed for rcm/rcup
tap thoughtbot/formulae

install ack
install archey
install cabal-install
install ccze
install checkbashisms
install clean
install coreutils
install ctags
install curl
install file-formula
install findutils
install git
install git-extras
install graphviz
install grep
install htop-osx
install hub
install less
install lesspipe
install md5sha1sum
install pandoc
install pidof
install pstree
install pwgen
install rbenv
install rcm
install readline
install reattach-to-user-namespace
install rename
install renameutils
install rsync
install ruby-build
install sqlite
install ssh-copy-id
install the_silver_searcher
install tidy
install tmux
install tofrodos
install tree
install unzip
install vim
install watch
install xmlstarlet
install zsh
install zsh-completions
install zsh-lovers
