#!/usr/bin/env zsh
#DESC# Node CLI applications #DESC#

set -euo pipefail

DOTFILES_DIR=~/.dotfiles
source "${DOTFILES_DIR}/local/include/hook-helpers.zsh"

cd "${DOTFILES_DIR}/tag-nodejs/bin"

# Rebuild scripts
for clicmd in *(.*N); do
  (./add-node-cli "$clicmd" || :) | offset &
done
wait

# Remove cache.
rm -rf "${HOME}/.cache/nodejs-cli-tool"
mkdir -p "${HOME}/.cache/nodejs-cli-tool"

# Install global packages
env TOOL_INSTALL=t ~/bin/yarn
~/bin/yarn global add neovim

# EOF
