#!/usr/bin/env zsh
#DESC# Node CLI applications #DESC#

set -euo pipefail

DOTFILES_DIR=~/.dotfiles
source "${DOTFILES_DIR}/local/include/hook-helpers.zsh"

cd "${DOTFILES_DIR}/tag-nodejs/bin"

# Rebuild scripts
./add-node-cli -u *(.*N)

# Remove cache.
rm -rf "${HOME}/.cache/nodejs-cli-tool"
mkdir -p "${HOME}/.cache/nodejs-cli-tool"

# Install global packages
yarn global add neovim

# EOF
