#!/usr/bin/env zsh
#DESC# docker completion files #DESC#

set -euo pipefail

DOTFILES_DIR=~/.dotfiles
source "${DOTFILES_DIR}/local/include/hook-helpers.zsh"

if ! (( ${+commands[docker]} + ${+functions[docker]} )); then
  print -P "  %F{yellow}Skipping%F{reset}: %F{green}docker%F{reset} isn't available"
  exit 0
fi

hh_curl \
  "Docker ZSH completion" \
  ~/.zsh/functions/_docker \
  https://raw.githubusercontent.com/docker/cli/master/contrib/completion/zsh/_docker &

hh_curl \
  "Docker-Compose ZSH completion" \
  ~/.zsh/functions/_docker-compose \
  https://raw.githubusercontent.com/docker/compose/master/contrib/completion/zsh/_docker-compose &

hh_curl \
  "Docker-Machine ZSH completion" \
  ~/.zsh/functions/_docker-machine \
  https://raw.githubusercontent.com/docker/machine/master/contrib/completion/zsh/_docker-machine &

wait

# EOF
