#!/usr/bin/env zsh
#DESC# Node.js packages #DESC#

set -eu

DOTFILES_DIR=~/.dotfiles
source "${DOTFILES_DIR}/local/include/hook-helpers.zsh"

if [[ -r ~/.zgen/zgen.zsh ]]; then
  export NVM_NO_USE=false
  set +eu
  source ~/.zgen/zgen.zsh
  set -eu
fi

packages=(

'npm-check'

# Builder
'gulpjs/gulp#4.0'


# JavaScript
'jscs'
'jshint'
'eslint'
'coffeelint'

# CSS
'csslint'
'stylelint'

# HTML
'htmlhint'

# Prose
'write-good'
)

if ! (( ${+commands[npm]} + ${+functions[npm]} )); then
  echo "Skipping, couldn't find 'npm'" 1>&2
  exit 0
fi

npm install --global "${packages[@]}"

npm upgrade --global

# EOF
