#!/usr/bin/env zsh
#DESC# tmux plugin manager and plugins #DESC#

set -euo pipefail

DOTFILES_DIR=~/.dotfiles
source "${DOTFILES_DIR}/local/include/hook-helpers.zsh"

if ! (( ${+commands[tmux]} )) > /dev/null; then
  print -P "  %F{yellow}Skipping%F{reset}: %F{green}tmux%F{reset} isn't available"
  exit 0
fi

hh_git 'Tmux Package Manager' https://github.com/tmux-plugins/tpm.git --dir=~/.tmux/plugins/tpm

if [ -d ~/.tmux/plugins ]; then
  pushd ~/.tmux/plugins > /dev/null
  for tmux_plugin in *(N/); do
    hh_git "tmux plugin ${tmux_plugin}" 'none' --dir=~/.tmux/plugins/"$tmux_plugin"
  done
  popd > /dev/null
fi

# EOF
