#!/usr/bin/env zsh
#DESC# vim plugins and plugin manager #DESC#

set -euo pipefail

DOTFILES_DIR=~/.dotfiles
source "${DOTFILES_DIR}/local/include/hook-helpers.zsh"

if ! (( $+commands[nvim] )) > /dev/null; then
  print -P "  %F{yellow}Skipping%F{reset}: %F{green}nvim%F{reset} isn't available"
  exit 0
fi

env \
  VIMRC_FORCE_BOOTSTRAP=1 \
  vim \
  -c ':set shortmess=at | :set cmdheight=4 | :if v:shell_error == 0 | :qa! | endif'

# EOF

