#!/usr/bin/env zsh
#DESC# yard documentation for Ruby gems #DESC#

set -euo pipefail

DOTFILES_DIR=~/.dotfiles
source "${DOTFILES_DIR}/local/include/hook-helpers.zsh"

if ! (( ${+commands[yard]} + ${+functions[yard]} )); then
  print -P "  %F{yellow}Skipping%F{reset}: %F{green}yard%F{reset} isn't available"
  exit 0
fi

yard gems --quiet || :

# EOF
