#!/usr/bin/env zsh
#DESC# zgen and its plugins #DESC#

set -eu

DOTFILES_DIR=~/.dotfiles
source "${DOTFILES_DIR}/local/include/hook-helpers.zsh"

setopt EXTENDED_GLOB

set +eu
source ~/.zgen/zgen.zsh
set -eu

echo
print -P "%F{cyan}z %F{blue}updating plugins %F{reset}"
set +eu
zgen update |& offset | colorize yellow
set -eu

# EOF
