#!/usr/bin/env zsh
#DESC# zplug and its plugins #DESC#

set -eu

DOTFILES_DIR=~/.dotfiles
source "${DOTFILES_DIR}/local/include/hook-helpers.zsh"

setopt EXTENDED_GLOB

set +eu
source ~/.zplug/init.zsh
set -eu

echo
print -P "%F{cyan}zplug %F{blue}updating... %F{reset}"
set +eu
zplug update
set -eu

# EOF
