#!/usr/bin/env zsh

set -eu

DOTFILES_DIR=~/.dotfiles
source "${DOTFILES_DIR}/local/include/hook-helpers.zsh"

if [ ! -f "${HOME}/.rcrc" ]; then
  echo "INFO: Installing default ~/.rcrc file" 1>&2
  cp "${DOTFILES_DIR}/rcrc.example" "${HOME}/.rcrc"
fi
