#!/usr/bin/env zsh

set -eu

DOTFILES_DIR=~/.dotfiles
source "${DOTFILES_DIR}/local/include/hook-helpers.zsh"

# Cleanup old cruft.
if [ -d "${DOTFILES_DIR}/vim/vimrc" ]; then
  rm -rf "${DOTFILES_DIR}/vim"
fi

# EOF
