#!/usr/bin/env zsh

set -eu

DOTFILES_DIR=~/.dotfiles
source "${DOTFILES_DIR}/local/include/hook-helpers.zsh"

if [[ ! -d ~/.zinit/bin/.git ]]; then
  mkdir -p ~/.zinit/{plugins,completions,services,snippets}
  hh_git 'ZInit' https://github.com/zdharma/zinit.git ~/.zinit/bin
fi

# EOF
