#!/usr/bin/env zsh

set -eu

DOTFILES_DIR=~/.dotfiles
source "${DOTFILES_DIR}/local/include/hook-helpers.zsh"

if [[ ! -f ~/.zplug/init.zsh ]]; then
  hh_git 'ZPlug' https://github.com/zplug/zplug.git ~/.zplug
fi

# EOF
