context           = 3
smart-case        = true
global-gitignore  = true
vcs-ignore        = [".gitignore"]

color             = true
color-line-number = "1;34"
color-path        = "1;32"
color-match       = "1;04;31"
