#!/usr/bin/env zsh

set -euo pipefail

DOTFILES_DIR=~/.dotfiles
source "${DOTFILES_DIR}/local/include/hook-helpers.zsh"

hh_git 'Tmux Package Manager' https://github.com/tmux-plugins/tpm.git ~/.tmux/plugins/tpm
