#!/usr/bin/env zsh

set -eu

setopt nullglob

declare -ar broken=(
  ~/.zsh/**/*(-@)
  ~/bin/**/*(-@)
  ~/.local/bin/**/*(-@)
  ~/.local/libexec/**/*(-@)
  ~/.local/share/**/*(-@)
  ~/.config/**/*(-@)
  ~/.*(-@)
)

if (( ${#broken[*]} > 0 )); then
  echo "Removing broken symlinks"
  rm -vf "${(@)broken}"
fi

# EOF
