#!/usr/bin/env zsh

set -eu

declare -a broken=(
  ~/.zsh/**/*(ND-@)
  ~/bin/**/*(ND-@)
  ~/.local/bin/**/*(ND-@)

  ~/.local/libexec/*(ND-@)
  ~/.local/libexec/*/*(ND-@)
  ~/.local/libexec/*/*/*(ND-@)
  ~/.local/libexec/*/*/*/*(ND-@)

  ~/.local/share/*(ND-@)
  ~/.local/share/*/*(ND-@)
  ~/.local/share/*/*/*(ND-@)
  ~/.local/share/*/*/*/*(ND-@)

  ~/.config/**/*(ND-@)
  ~/*(ND-@)
)

if (( ${#broken[*]} > 0 )); then
  echo "Removing broken symlinks"
  {
    # Needs to work with macOS & GNU `find`.
    # Detects broken symlinks from */.dotfiles*/ specificially.
    find -L "${(@)broken}" -type l -lname '*/.dotfiles*' -exec rm -vf '{}' '+'
  } 2>&1 | offset
fi

# EOF
