#!/usr/bin/env zsh

set -eu

# Wildcards will apply to hidden files.
setopt GlobDots

# Wildcards with no match don't error.
setopt NullGlob

declare -a broken=(
  ~/.zsh/**/*(-@)
  ~/.bash/**/*(-@)
  ~/bin/**/*(-@)
  ~/.local/bin/**/*(-@)

  ~/.local/libexec/*(-@)
  ~/.local/libexec/*/*(-@)
  ~/.local/libexec/*/*/*(-@)
  ~/.local/libexec/*/*/*/*(-@)

  ~/.local/share/*(-@)
  ~/.local/share/*/*(-@)
  ~/.local/share/*/*/*(-@)
  ~/.local/share/*/*/*/*(-@)

  ~/.local/share/zinit/**/*(-@)

  ~/.ssh/**/*(-@)

  ~/.config/**/*(-@)
  ~/*(-@)
  ~/.*(-@)
)

if (( ${#broken[*]} > 0 )); then
  echo "Removing broken symlinks"
  {
    # Needs to work with macOS & GNU `find`.
    # Detects broken symlinks from */.dotfiles*/ specificially.
    find -L "${(@)broken}" -type l -lname '*/.dotfiles*' -exec rm -vf '{}' '+'
  } 2>&1 | offset
fi

# EOF
