#!/usr/bin/env zsh

set -eu

DOTFILES_DIR="$(dirname "$(dirname "$(dirname "$0")")")"
source "${DOTFILES_DIR}/bin/hook-helpers.zsh"

hh_git 'Oh My Zsh' https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
