#!/usr/bin/env zsh

set -eu

DOTFILES_DIR=~/.dotfiles
source "${DOTFILES_DIR}/bin/hook-helpers.zsh"

hh_git 'Zsh Syntax Highlighting' \
  https://github.com/zsh-users/zsh-syntax-highlighting.git \
  "${HOME}/.zsh/plugins/zsh-syntax-highlighting"
