#!/usr/bin/env zsh

set -eu

DOTFILE_DIR="$(dirname "$(dirname "$(dirname "$0")")")"
source "${DOTFILE_DIR}/bin/hook-helpers.zsh"

hh_git 'Zsh Syntax Highlighting' \
  https://github.com/zsh-users/zsh-syntax-highlighting.git \
  "${HOME}/.zsh/plugins/zsh-syntax-highlighting"
